web:
 image: nginx:latest
 ports:
 - "80:80"
 volumes:
 - ./code:/code
 - ./default.conf:/etc/nginx/conf.d/default.conf
 links:
 - php
 - mysqldb
php:
 image: php:7-fpm
 volumes:
 - ./code:/code
mysqldb:
 image: mysql
 container_name: mysql
 environment:
 - MYSQL_DATABASE=enuygun
 - MYSQL_ROOT_PASSWORD=trustno1
 - MYSQL_USER=developer
 - MYSQL_PASSWORD=developer
 ports:
 - 3306:3306